version: '3'

services:
  traefik:
    image: "traefik:v2.2"
    container_name: "traefik"
    command:
      - "--log.level=DEBUG"
      - "--api.insecure=true"
      - "--providers.docker=true"
      - "--providers.docker.exposedbydefault=false"
      - "--entrypoints.web.address=:80"
      - "--entrypoints.websecure.address=:443"
      - "--certificatesresolvers.myresolver.acme.httpchallenge=true"
      - "--certificatesresolvers.myresolver.acme.httpchallenge.entrypoint=web"
      - "--certificatesresolvers.myresolver.acme.caserver=https://acme-staging-v02.api.letsencrypt.org/directory"
      - "--certificatesresolvers.myresolver.acme.email=willis8@illinois.edu"
      - "--certificatesresolvers.myresolver.acme.storage=/letsencrypt/acme.json"
      - "--entrypoints.web.http.redirections.entrypoint.to=websecure"
      - "--entrypoints.web.http.redirections.entrypoint.scheme=https"
    ports:
      - "80:80"
      - "443:443"
      - "8080:8080"
    volumes:
      - "./letsencrypt:/letsencrypt"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"

  api:
    image: geocodes/p418services
    ports:
      - 6789
    environment:
      - GEODEX_HOST=geodex.local.earthcube.org
    volumes:
      - "/bleve:/indexes:ro"
      - "./indexcatalog.json:/indexcatalog.json"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.api.rule=Host(`geodex.local.earthcube.org`) && PathPrefix(`/api`)"
      - "traefik.http.routers.api.entrypoints=websecure"
      - "traefik.http.routers.api.tls=true"
      - "traefik.http.routers.api.tls.certresolver=myresolver"

  geodex:
    image: geocodes/p418webui
    environment:
      - GEODEX_HOST=geodex.local.earthcube.org
    ports:
      - 9900
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geodex.rule=Host(`geodex.local.earthcube.org`)"
      - "traefik.http.routers.geodex.entrypoints=websecure"
      - "traefik.http.routers.geodex.tls=true"
      - "traefik.http.routers.geodex.tls.certresolver=myresolver"

  geocodes:
    image: geocodes/p418webui2
    environment:
      - GEODEX_HOST=geodex.local.earthcube.org
    ports:
      - 80
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.geocodes.rule=Host(`geodex.local.earthcube.org`) && PathPrefix(`/geocodes`)"
      - "traefik.http.routers.geocodes.entrypoints=websecure"
      - "traefik.http.routers.geocodes.tls=true"
      - "traefik.http.routers.geocodes.tls.certresolver=myresolver"

  tile38:
    image: tile38/tile38
    ports:
     - 9851
    volumes:
      - "/home/ubuntu/go/src/earthcube.org/Project418/gleaner/docs/starterpack/DV/spatialindex:/data"
